# Generated by Django 3.1.2 on 2020-10-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testformset', '0002_answerquestion_questiontest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerquestion',
            options={'ordering': ['prefix_name']},
        ),
        migrations.RenameField(
            model_name='answerquestion',
            old_name='prefix',
            new_name='prefix_name',
        ),
    ]
